application: spsc-hrd
version: 2-2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: (/|/all|/view|/edit|/delete|/mine|/authors|/author|/svg|/supercompiler|/svgpreview)
  script: main.app
